import {StyleSheet} from 'react-native';

import {colors} from '../../../../shared/theme';

export const styles = StyleSheet.create({
  touchTarget: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  visual: {
    width: 38,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  body: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(253,251,244,0.92)',
    shadowColor: colors.brandDeepForest,
    shadowOpacity: 0.15,
    shadowRadius: 4,
    shadowOffset: {width: 0, height: 2},
    elevation: 3,
  },
  shield: {
    width: 31,
    height: 34,
    top: 2,
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    borderBottomLeftRadius: 11,
    borderBottomRightRadius: 11,
  },
  shieldTip: {
    position: 'absolute',
    width: 9,
    height: 9,
    bottom: 3,
    transform: [{rotate: '45deg'}],
    borderBottomRightRadius: 3,
  },
  diamond: {
    width: 29,
    height: 29,
    borderRadius: 9,
    transform: [{rotate: '45deg'}],
  },
  diamondGlyph: {
    transform: [{rotate: '-45deg'}],
  },
  workSign: {
    width: 34,
    height: 29,
    borderRadius: 8,
    transform: [{perspective: 90}, {rotateX: '-7deg'}],
  },
  workBase: {
    position: 'absolute',
    bottom: 5,
    width: 27,
    height: 3,
    borderRadius: 2,
  },
  barrier: {
    width: 38,
    height: 23,
    borderRadius: 8,
  },
  triangle: {
    width: 0,
    height: 0,
    borderLeftWidth: 17,
    borderRightWidth: 17,
    borderBottomWidth: 31,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderRadius: 7,
  },
  triangleGlyph: {
    position: 'absolute',
    top: 15,
  },
  stackedRoadBack: {
    position: 'absolute',
    width: 29,
    height: 12,
    borderRadius: 6,
    top: 9,
    left: 3,
    opacity: 0.72,
    transform: [{rotate: '-7deg'}],
  },
  stackedRoadFront: {
    width: 32,
    height: 18,
    borderRadius: 8,
    top: 5,
    left: 2,
    transform: [{rotate: '5deg'}],
  },
  roadTile: {
    width: 37,
    height: 22,
    borderRadius: 9,
  },
  trafficLight: {
    width: 23,
    height: 36,
    borderRadius: 9,
  },
  serviceHex: {
    width: 32,
    height: 28,
    borderRadius: 10,
    transform: [{rotate: '30deg'}],
  },
  serviceGlyph: {
    transform: [{rotate: '-30deg'}],
  },
  pebble: {
    width: 30,
    height: 29,
    borderTopLeftRadius: 11,
    borderTopRightRadius: 8,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 12,
    transform: [{rotate: '-4deg'}],
  },
  pebbleGlyph: {
    transform: [{rotate: '4deg'}],
  },
  stale: {
    opacity: 0.58,
  },
  unconfirmed: {
    opacity: 0.76,
  },
  doubtfulAccent: {
    position: 'absolute',
    bottom: 3,
    width: 20,
    height: 2.5,
    borderRadius: 2,
    backgroundColor: '#B94A50',
  },
  selectedHalo: {
    position: 'absolute',
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: 'rgba(21,61,50,0.26)',
    backgroundColor: 'rgba(79,138,88,0.08)',
  },
  glyph: {
    width: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  glyphLine: {
    position: 'absolute',
    height: 2.2,
    borderRadius: 2,
    backgroundColor: colors.textInverse,
  },
  glyphDot: {
    position: 'absolute',
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.textInverse,
  },
  beaconBase: {width: 14, top: 10},
  beaconCap: {width: 9, top: 5},
  beaconDot: {top: 1},
  impactLine: {width: 16, transform: [{rotate: '45deg'}]},
  impactLineOpposite: {width: 16, transform: [{rotate: '-45deg'}]},
  worksHandle: {width: 15, transform: [{rotate: '-55deg'}]},
  worksBase: {width: 9, top: 12},
  worksDot: {top: 1, right: 1},
  blockedBase: {width: 17},
  blockedSlash: {width: 9, transform: [{rotate: '-55deg'}]},
  warningStem: {width: 2.4, height: 9, top: 2},
  warningDot: {bottom: 1},
  trafficTop: {width: 13, top: 4, left: 1},
  trafficBottom: {width: 13, bottom: 4, right: 1},
  trafficTopDot: {top: 3, right: 0},
  trafficBottomDot: {bottom: 3, left: 0},
  signalTop: {top: 0},
  signalBottom: {bottom: 0},
  serviceLine: {width: 15},
  serviceLineVertical: {width: 15, transform: [{rotate: '90deg'}]},
  moreLeft: {left: 1},
  moreRight: {right: 1},
  roadCenter: {width: 15, transform: [{rotate: '90deg'}]},
  roadLeft: {width: 8, left: 1},
  roadRight: {width: 8, right: 1},
});
