import { TELEGRAM_BOOTSTRAP_HISTORY_LIMIT } from '../telegram.constants';

export const TELEGRAM_RUNTIME_CONTEXT_SEED_LIMIT =
  TELEGRAM_BOOTSTRAP_HISTORY_LIMIT;

export const TELEGRAM_RUNTIME_CONTEXT_CAPACITY = 50;

export const TELEGRAM_RUNTIME_MAX_IN_FLIGHT = 100;

export const TELEGRAM_RUNTIME_SHUTDOWN_TIMEOUT_MS = 5_000;

export const TELEGRAM_INGESTION_ENABLED_ENV = 'TELEGRAM_INGESTION_ENABLED';

export const TELEGRAM_REVIEW_LOGS_ENABLED_ENV = 'TELEGRAM_REVIEW_LOGS_ENABLED';

export const TELEGRAM_REVIEW_LOG_DIR_ENV = 'TELEGRAM_REVIEW_LOG_DIR';

export const TELEGRAM_REVIEW_LOG_DIR_DEFAULT = 'runtime-logs/telegram';

export const TELEGRAM_REVIEW_LOG_FILE_MAX_BYTES = 20 * 1024 * 1024;

export const TELEGRAM_REVIEW_LOG_DEDUP_LIMIT = 10_000;
