from base64 import b64decode
from pathlib import Path

OUTPUT_DIR = Path(__file__).resolve().parent.parent / "src" / "assets" / "map-events"

ICONS = {
    "accident.png": (
        "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAABZUlEQVR4nO2YSxIDIQhEh1Tuf2WySRaZUoFGxUr6LUdlpAX8XBchhBBCCCGEkP9DqifQQ1VVRERV1er76SciYX+OFMDjdI+oCA/0R7/CcQJkVh8Zf0QKWPk+CmtkzFc/3xT7ZIuUNd7jSEYEOAUiofbpex8zw/lIvxaQAD2HEBs9ok4h0XVdYApkC1VzIs49P2rT7BM12pokUqR641eJ22tLb4OWytn21YQEQFen5+T9+4rVt+w+M4Yjq9fKcev8nokOr5huAVoGs2d2fYPamIEpwO6itJvj7gK7GUbAyqIkb3b8b0SoCO4oSrspTYETRCkTYMZ9Ygapc8As0KvyDI7ZBdBHTQ9L7wIoVSt+pzQC7iJUHJDKa0DkTT977W7aHDWuDMmoM+jboDVumAIVRanVjr4NTnkR+vvLUOvM/ktMKYKnbGkI7m3Q+6yFfq8idA6IFpkT9nlCCCGEEEIIIYQQQr55ASHl3G2vL9atAAAAAElFTkSuQmCC"
    ),
    "closure.png": (
        "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAhklEQVR4nO3XMRKAIAwEQPD/f8aKxipxnIHIbi3O5UihrQEAAAAAAByivz04xhhfBvlC7z09T/rAjoM/ZYq4Mi+uMHxruZzhAqoMP0Xzpjbgj0IFVLv9KZLbBqwOsJoCVgdYLVTAmy+sHURy24Dog9W2IJo3tQFVSsjkPP5vEAAAAAAAOMcNLUkkHA7ZSvsAAAAASUVORK5CYII="
    ),
    "roadworks.png": (
        "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAABLklEQVR4nO2ZwQrDMAxDnbH//+XsVCglLdtsSQ7oXXqLU1mKUxphjDHGGGOMYTLnnOeniqEounrpMYZkLy9F0U5YAPUG1NAFuDv0VIehHaDewBmFC6gCqGf+CqkDVLP/TKsIRPBdIhdA7QKaAB3zHyF0wFPnmWLJIxChjQFFgH86ynKBxAGrjvtzWARcgIyVGTGgO+DJ6ooYOALIxSssjI7BG7n4im43wi0igBQNJkC3Tt+xhQOQwMbO1QG/jjjWz5O2DmDdCSAC7JL/CJIDqrqJELZtBCI4MSgXAG3/6vXhDsh2Ee2C1hFgUCoA6/SvrAP/GOo+EksdwLq8VNZpO5+/JStG2gFqi2frpwRQv/xBZh8eg+oNqEkJoP61fZDZR9oBahHU9Y0xxhhjtuUDqd2EMNy1+J4AAAAASUVORK5CYII="
    ),
    "traffic.png": (
        "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAABSUlEQVR4nO2YwQ7EIAhEdbP//8vs3bhWYQqTOO9aY4UOg7Q1IYQQQghxJ736ACNmZqvnvXfomT/IzaI8Bb+75gSqBFRAUwLjlx2l/vTcy/UKoEjAztd9UoSXsIyirh0JBFEGIQVEXTv6FREqKCsBlISj+3xRL17VqJnZSq4eKaMSSGGClbgSUOnaaI5LYBYIa3A7HCmAwbXRbCeAxbXRuLpApWujcbdBJJXJKWuDqGkuuk/pPSB6eEQSKUpgZBbYU/v1JqP8JjgefDd4z5oZFApA/+g8evfuQqRTnwT89q+y7RJgcW00Rx6Q7doZQxfEA7zGtSJr6DruAjuufbJuRubQRVWPreWbLUUb/EfG0FV+EapGCag+QDVKQPUBqrk+AdRtMONXGZ0CsocuugS0ljt0UZfAyBtDF6UCWssZuoQQQgghhBBC3MoPN2m8YLF4Jx8AAAAASUVORK5CYII="
    ),
    "hazard.png": (
        "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAABhklEQVR4nO2a2wrDMAxD2/3/P2dPhRGWqyU5FJ23QYldWZ7TtNdljDHGGGOMlFJK6f1WcWcE7d3sfd/SnD7KYCciF2BkdXUrpDtAbfkaqQCz1VW6INUBT/UzXSATYLWqKhdIBPh3M3XV/7lAIUJKC7Qsn9EKdAGiVWS7QO6AUZVftRNEVY/pAqkD6uqWH3rXMaEJsLrlzdoiUwSYGXsjVGNR0gK7lla0AlwA9thCr093QLSKbBdABVDt35FxqA5AVY/pApgA6pMcVDyIAIixN4I1FiktwLIsY92wAFnn+aj4cAewxxZ6/ZAA2dV/iOQBdYDqKQ4ZZ1uAaPVnzgQV+WwFVYw9VR6QFsg610fEXRbglD++Fqv5hR2Q/W4vGn9JAHT1W2eCiHVnrw05IKI+8guRSB7TAiCr1FpLEaNmSoBTxl6P3afFrRY47eYfdvIaCsAYe8qXo6P8lx3AOubKOj7rXnz6pmeFljDpH0ll0xTgTdW/rvb9DPvlDUKcOrWMMcYYY0wmXwcU9CczrI+BAAAAAElFTkSuQmCC"
    ),
    "traffic-light.png": (
        "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAABPElEQVR4nO2bwQrDMAxDlbH//+XsFAhZk9JgyYXo3Uq7OlZju4IOMMYYY46lqALVWuvT35RS6OujB9hJfIQpxId1YyAm+cj7XEETIHrRLBG+jJvOeLKVmU+9h7IDrhb/tI6vrmeIQu0Bjd0mppgC0hLoidglEUh2wMhsK6vqvkcuwF2SahGkAozJlY7VdUxSSgD4r/eM+gcSBXgLFiAr8FjnGRMASHgV7hOdJa3sB/IdcJecuhmmlMAsyYxJkPYqnDX2Ro6fAjZD6oCAzZDNUMNmaHGs4vgpYAGyAtsMwWZo63w0NkPqgA2boZdgM6QOCNgM2Qw1bIYWxyqOnwIWICuwzRBshrbOR2MzpA7YOMoM7TY4RWOkCBDxkaPKLElLIGvUraCVQPTTYvUMag+IWjSzYR7/jxFjjDEn8wPNksCOl/4E0QAAAABJRU5ErkJggg=="
    ),
    "road-service.png": (
        "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAABSUlEQVR4nO2YyY6DQAwFy/P//8xcMtIIhUDb7sWdV6coIS1VsRlACCGEEEIIIYQQVTiO48hY5ydjkdH8yWdEKBfgLB2NUCrAlWwkQpkAnyTNzLzrlgjQSx4g9Ofe3B3aUXlY+AgYIQ+LBhglDwsGeHJFzxqCYLEALWLbTYIeoW0mwYhI+UnwiYC9iKxxxdQAT+Xfffas9Y5pAVrlP33XsuaZKQG88ne/eeaD4QGi8lfbeIejoQGy5M/bRibDYQ9D2fJZDDkCVpWHAQFWlofOAVaXh44BKshDpwBV5KFDgErykBygmjwkBqgoD8FBqOXhY0V5CBwBO8iDM8Au8uAIsJM8NAZofeGQ+fq6F6G7QIU9fEf4Nlg9QsockPFiYhahAP/PcTOzCuf8meY99tV3AXguVUEenKfAnVwVeQhcAzLfzQshhBBCzOAXttq8RRJl/RgAAAAASUVORK5CYII="
    ),
    "other.png": (
        "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAb0lEQVR4nO3WwQqAIBAFQO3//9luEZQmGSvkzFXeY1ERUwIAAAAAAABWkL8qKqWUozTnrt6oTMtwwXmgS3llwKhMj+1t8C+GNqB1KrX1qEwvN2D2ALMNbcDT43O3HpXptfwNWP4fAAAAAAAAAIvYAV09PBCWLtNoAAAAAElFTkSuQmCC"
    ),
    "cluster.png": (
        "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAABG0lEQVR4nO2aQQKDIAwEof//Mz1xwSpEsgTrzLWwbJZIazUlAAAAAHgnOWLRUko5+yznvNTT0sWuCm9ZFcSSRSyFt6iD+CjFU5or3mN+D2kAXuaVIcgC8DatCkF+CeyOJADVbil06QBvQfWp7a1PB0QbiIYAog1E4/I7W33wXTF7rzA1ObLwlrtB3Jq0U+Et1iDMZ8DOxadk92cKYPfiKxafwwE8pfjKqN/Xfw0OBfC03a+M+KYDegOeuvuVnn86INpANAQQbSAaAog2EE03APWzuWh9OmBkkGqXqq5a/wo6YHSg9y61emr9M0wd4GXyTEet/wvzJTD9L2xnvlr/MH5mMfU7PyveKZI/F/Bo653eKgMAAAAAAAD4A74bOXhDPi24MwAAAABJRU5ErkJggg=="
    ),
}


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    for filename, encoded in ICONS.items():
        path = OUTPUT_DIR / filename
        path.write_bytes(b64decode(encoded))
        print(f"created {path}")


if __name__ == "__main__":
    main()