export const TELEGRAM_RUNTIME_DEDUP_LIMIT = 5_000;

export const TELEGRAM_BOOTSTRAP_HISTORY_LIMIT = 30;

export const TELEGRAM_MAX_HISTORY_LIMIT = 50;

export const TELEGRAM_RECOVERY_MAX_MESSAGES = 200;

export const TELEGRAM_RECOVERY_CURSOR_OVERLAP = 2;

export const TELEGRAM_CONNECTION_RETRIES = 5;

export const TELEGRAM_RECONNECT_RETRIES = 10;
